version: "3.8"

services:
  app:
    build:
      context: .
      target: ${TARGET_STAGE:-development}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - YF_API_KEY=${YF_API_KEY}
      - BASE_URL=${BASE_URL}
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: >
      sh -c "if [ ${NODE_ENV} = 'development' ]; then npm run dev; else npm run start; fi"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
